//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlazorAppServer.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BlazorAppServer.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Academic Email.
        /// </summary>
        public static string AcademicEmail {
            get {
                return ResourceManager.GetString("AcademicEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access your official university email for important updates, communications, and announcements regarding your application..
        /// </summary>
        public static string AcademicEmailinfo {
            get {
                return ResourceManager.GetString("AcademicEmailinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access your academic email to stay connected with faculty, receive course updates, and manage university communications..
        /// </summary>
        public static string AcademicEmailstudent {
            get {
                return ResourceManager.GetString("AcademicEmailstudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age.
        /// </summary>
        public static string Age {
            get {
                return ResourceManager.GetString("Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applicant.
        /// </summary>
        public static string Applicant {
            get {
                return ResourceManager.GetString("Applicant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applicant Registration.
        /// </summary>
        public static string ApplicantRegistration {
            get {
                return ResourceManager.GetString("ApplicantRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applicants.
        /// </summary>
        public static string Applicants {
            get {
                return ResourceManager.GetString("Applicants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Requirements.
        /// </summary>
        public static string ApplicationRequirements {
            get {
                return ResourceManager.GetString("ApplicationRequirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review the essential documents and criteria needed to complete your application process successfully..
        /// </summary>
        public static string ApplicationRequirementsinfo {
            get {
                return ResourceManager.GetString("ApplicationRequirementsinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bifurcation Services.
        /// </summary>
        public static string BifurcationServices {
            get {
                return ResourceManager.GetString("BifurcationServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn more about bifurcation options available for students to split their course load across multiple semesters or academic terms..
        /// </summary>
        public static string BifurcationServicesinfo {
            get {
                return ResourceManager.GetString("BifurcationServicesinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee.
        /// </summary>
        public static string Employee {
            get {
                return ResourceManager.GetString("Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Registration.
        /// </summary>
        public static string EmployeeRegistration {
            get {
                return ResourceManager.GetString("EmployeeRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employees.
        /// </summary>
        public static string Employees {
            get {
                return ResourceManager.GetString("Employees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your age.
        /// </summary>
        public static string Enteryourage {
            get {
                return ResourceManager.GetString("Enteryourage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your modile.
        /// </summary>
        public static string Enteryourmodile {
            get {
                return ResourceManager.GetString("Enteryourmodile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your name.
        /// </summary>
        public static string Enteryourname {
            get {
                return ResourceManager.GetString("Enteryourname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your role.
        /// </summary>
        public static string Enteryourrole {
            get {
                return ResourceManager.GetString("Enteryourrole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your Scholarship.
        /// </summary>
        public static string EnteryourScholarship {
            get {
                return ResourceManager.GetString("EnteryourScholarship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your school name.
        /// </summary>
        public static string Enteryourschoolname {
            get {
                return ResourceManager.GetString("Enteryourschoolname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explore Options.
        /// </summary>
        public static string ExploreOptions {
            get {
                return ResourceManager.GetString("ExploreOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faculty Staff.
        /// </summary>
        public static string FacultyStaff {
            get {
                return ResourceManager.GetString("FacultyStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faculty Staff Registration.
        /// </summary>
        public static string FacultyStaffRegistration {
            get {
                return ResourceManager.GetString("FacultyStaffRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to Email.
        /// </summary>
        public static string GotoEmail {
            get {
                return ResourceManager.GetString("GotoEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information Table.
        /// </summary>
        public static string InformationTable {
            get {
                return ResourceManager.GetString("InformationTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Description Guide.
        /// </summary>
        public static string JobDescriptionGuide {
            get {
                return ResourceManager.GetString("JobDescriptionGuide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guidelines for writing effective job descriptions..
        /// </summary>
        public static string JobDescriptionGuideinfo {
            get {
                return ResourceManager.GetString("JobDescriptionGuideinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jobs.
        /// </summary>
        public static string Jobs {
            get {
                return ResourceManager.GetString("Jobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explore job opportunities and descriptions..
        /// </summary>
        public static string Jobsinfo {
            get {
                return ResourceManager.GetString("Jobsinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Accommodation.
        /// </summary>
        public static string ManageAccommodation {
            get {
                return ResourceManager.GetString("ManageAccommodation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        public static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operations.
        /// </summary>
        public static string Operations {
            get {
                return ResourceManager.GetString("Operations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Services .
        /// </summary>
        public static string Ourservices {
            get {
                return ResourceManager.GetString("Ourservices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Guide.
        /// </summary>
        public static string ReadGuide {
            get {
                return ResourceManager.GetString("ReadGuide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register as a/an.
        /// </summary>
        public static string Registerasa_an {
            get {
                return ResourceManager.GetString("Registerasa/an", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered Applicants.
        /// </summary>
        public static string RegisteredApplicants {
            get {
                return ResourceManager.GetString("RegisteredApplicants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered Employees.
        /// </summary>
        public static string RegisteredEmployees {
            get {
                return ResourceManager.GetString("RegisteredEmployees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered Students.
        /// </summary>
        public static string RegisteredStudents {
            get {
                return ResourceManager.GetString("RegisteredStudents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scholarships.
        /// </summary>
        public static string Scholarships {
            get {
                return ResourceManager.GetString("Scholarships", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explore a range of scholarship opportunities available to applicants and check the status of your current applications..
        /// </summary>
        public static string Scholarshipsinfo {
            get {
                return ResourceManager.GetString("Scholarshipsinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scholarship Type.
        /// </summary>
        public static string ScholarshipType {
            get {
                return ResourceManager.GetString("ScholarshipType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondary School Name.
        /// </summary>
        public static string SecondarySchoolName {
            get {
                return ResourceManager.GetString("SecondarySchoolName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Transfer.
        /// </summary>
        public static string StartTransfer {
            get {
                return ResourceManager.GetString("StartTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Statement.
        /// </summary>
        public static string StatusStatement {
            get {
                return ResourceManager.GetString("StatusStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With supporting text below as a natural lead-in to additional content..
        /// </summary>
        public static string StatusStatementinfo {
            get {
                return ResourceManager.GetString("StatusStatementinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student.
        /// </summary>
        public static string Student {
            get {
                return ResourceManager.GetString("Student", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Accommodation.
        /// </summary>
        public static string StudentAccommodation {
            get {
                return ResourceManager.GetString("StudentAccommodation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find accommodation options on and off-campus, and submit your housing application or manage existing requests..
        /// </summary>
        public static string StudentAccommodationinfo {
            get {
                return ResourceManager.GetString("StudentAccommodationinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Affairs Management System.
        /// </summary>
        public static string StudentAffairsManagementSystem {
            get {
                return ResourceManager.GetString("StudentAffairsManagementSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Registration.
        /// </summary>
        public static string StudentRegistration {
            get {
                return ResourceManager.GetString("StudentRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Students.
        /// </summary>
        public static string Students {
            get {
                return ResourceManager.GetString("Students", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer Service.
        /// </summary>
        public static string TransferService {
            get {
                return ResourceManager.GetString("TransferService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discover how to transfer between different departments or universities and manage your transfer application..
        /// </summary>
        public static string TransferServiceinfo {
            get {
                return ResourceManager.GetString("TransferServiceinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Details.
        /// </summary>
        public static string ViewDetails {
            get {
                return ResourceManager.GetString("ViewDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Jobs.
        /// </summary>
        public static string ViewJobs {
            get {
                return ResourceManager.GetString("ViewJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Selim University.
        /// </summary>
        public static string WelcometoSelimUniversity {
            get {
                return ResourceManager.GetString("WelcometoSelimUniversity", resourceCulture);
            }
        }
    }
}
